---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: nodeapp-git-repo
  namespace: flux-system
spec:
  image: alicechang/nodeapp-git
  interval: 30s
  secretRef:
    name: dockerhub-cred
